name: deploy

on:
  push:
    branches:
      - "main"
      - "next"

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  RELEASE_NAME: trader4-bridge
  RELEASE_NAMESPACE: trader4-bridge
  RELEASE_DOMAIN: bridge.trader4.net
  NEXT_RELEASE_DOMAIN: next-bridge.trader4.net
  WSS_RELEASE_DOMAIN: wss.trader4.net
  NEXT_WSS_RELEASE_DOMAIN: next-wss.trader4.net

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint .ci/chart
  build:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Lowecase the repo name
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Declare short commit id
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "Set IMG_NAME variable"
        run: echo 'IMG_NAME=ghcr.io/${{ env.REPOSITORY_NAME }}' >>$GITHUB_ENV

      - name: "Set IMG_TAG variable"
        run: echo 'IMG_TAG=${{ env.BRANCH_NAME }}-${{ steps.vars.outputs.sha_short }}' >>$GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMG_NAME }}:${{ env.IMG_TAG }}

  helm:
    needs: [build]
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Lowecase the repo name
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Declare short commit id
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "Set IMG_NAME variable"
        run: echo 'IMG_NAME=ghcr.io/${{ env.REPOSITORY_NAME }}' >>$GITHUB_ENV

      - name: "Set IMG_TAG variable"
        run: echo 'IMG_TAG=${{ env.BRANCH_NAME }}-${{ steps.vars.outputs.sha_short }}' >>$GITHUB_ENV

      - name: "Set RELEASE_DOMAIN to next if branch is next"
        if: env.BRANCH_NAME == 'next'
        run: echo 'RELEASE_DOMAIN=${{ env.NEXT_RELEASE_DOMAIN }}' >>$GITHUB_ENV

      - name: "Set WSS_RELEASE_DOMAIN to next if branch is next"
        if: env.BRANCH_NAME == 'next'
        run: echo 'WSS_RELEASE_DOMAIN=${{ env.NEXT_WSS_RELEASE_DOMAIN }}' >>$GITHUB_ENV

      - name: "Set RELEASE_NAME if to next branch is next"
        if: env.BRANCH_NAME == 'next'
        run: echo 'RELEASE_NAME=next-${{ env.RELEASE_NAME }}' >>$GITHUB_ENV

      - name: Run Helm and Deploy on Main
        uses: WyriHaximus/github-action-helm3@v3
        if: env.BRANCH_NAME == 'main'
        with:
          exec: |
            helm upgrade --install \
              "${{ env.RELEASE_NAME }}.${{ env.BRANCH_NAME }}" \
              --namespace ${{ env.RELEASE_NAMESPACE }} \
              --set name="${{ env.RELEASE_NAME }}" \
              --set domainName="${{ env.RELEASE_DOMAIN }}" \
              --set wssDomainName="${{ env.WSS_RELEASE_DOMAIN }}" \
              --set image.repository="${{ env.IMG_NAME }}" \
              --set image.tag="${{ env.IMG_TAG }}" \
              --set tls.enabled="true" \
              --set tls.clusterIssuer="cf-letsencrypt" \
              --set tls.secretName="${{ env.BRANCH_NAME }}-${{ env.RELEASE_NAME }}-net-tls" \
              --set app.name="Trader4-Bridge" \
              --set app.jwt.secret="${{ secrets.APP_JWT_SECRET }}" \
              --set app.secret="${{ secrets.APP_SECRET }}" \
              --set app.url="${{ env.RELEASE_DOMAIN }}" \
              --set app.env="${{ secrets.APP_ENV }}" \
              --set app.kafka.broker="${{ secrets.KAFKA_BROKER }}" \
              --set app.kafka.topic="${{ secrets.KAFKA_TOPIC }}" \
              --set app.kafka.group_id="${{ secrets.KAFKA_GROUP_ID }}" \
              --set app.mongodb.uri="${{ secrets.APP_MONGODB_URI }}" \
              --set app.redis.host="${{ secrets.APP_REDIS_HOST }}" \
              --set app.redis.port="${{ secrets.APP_REDIS_PORT }}" \
              --set app.webhook_url="${{ secrets.APP_WEBHOOK_URL }}" \
              --set app.check_auth_werify="${{ secrets.APP_CHECK_AUTH_WERIFY }}" \
              --create-namespace \
              --atomic \
              .ci/chart
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Run Helm and Deploy on Next
        uses: WyriHaximus/github-action-helm3@v3
        if: env.BRANCH_NAME == 'next'
        with:
          exec: |
            helm upgrade --install \
              "${{ env.RELEASE_NAME }}.${{ env.BRANCH_NAME }}" \
              --namespace ${{ env.RELEASE_NAMESPACE }} \
              --set name="${{ env.RELEASE_NAME }}" \
              --set domainName="${{ env.RELEASE_DOMAIN }}" \
              --set wssDomainName="${{ env.WSS_RELEASE_DOMAIN }}" \
              --set image.repository="${{ env.IMG_NAME }}" \
              --set image.tag="${{ env.IMG_TAG }}" \
              --set tls.enabled="true" \
              --set tls.clusterIssuer="cf-letsencrypt" \
              --set tls.secretName="${{ env.BRANCH_NAME }}-${{ env.RELEASE_NAME }}-net-tls" \
              --set app.name="Trader4-Next-Bridge" \
              --set app.jwt.secret="${{ secrets.NEXT_APP_JWT_SECRET }}" \
              --set app.secret="${{ secrets.NEXT_APP_SECRET }}" \
              --set app.url="${{ env.RELEASE_DOMAIN }}" \
              --set app.env="${{ secrets.NEXT_APP_ENV }}" \
              --set app.kafka.broker="${{ secrets.NEXT_KAFKA_BROKER }}" \
              --set app.kafka.topic="${{ secrets.NEXT_KAFKA_TOPIC }}" \
              --set app.kafka.group_id="${{ secrets.NEXT_KAFKA_GROUP_ID }}" \
              --set app.mongodb.uri="${{ secrets.NEXT_APP_MONGODB_URI }}" \
              --set app.redis.host="${{ secrets.NEXT_REDIS_HOST }}" \
              --set app.redis.port="${{ secrets.NEXT_REDIS_PORT }}" \
              --set app.webhook_url="${{ secrets.NEXT_WEBHOOK_URL }}" \
              --set app.check_auth_werify="${{ secrets.APP_CHECK_AUTH_WERIFY }}" \
              --create-namespace \
              --atomic \
              .ci/chart
          kubeconfig: '${{ secrets.KUBECONFIG }}'
